name: Main build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true  # Checkout submodules

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++-12 libx11-dev libxext-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libgl1-mesa-dev libwayland-dev wayland-protocols

    - name: Set up GCC 12
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 60
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 60

    - name: Set up CMake
      uses: lukka/get-cmake@latest

    - name: Configure CMake
      run: cmake -B build -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: ctest --test-dir build
